const contractAddress = "0x3b7eDb34B0bc60C2B88FB6CCd0fa3443B61a4EDF"; //Replace with your own contract address
const chain = 'rinkeby'; // rinkeby or polygon

const welcome_h1 = "Nice to finally meet you!";
//const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = "Once upon a time there was a magical island that lived in a little girl's head. The island was occupied by the most happiest and magical creatures. The girl thought that the island was long gone. Until recently… In the hardest of times the island was found…by that same girl, but it wasn't a dream anymore. It was as real as these words in front of you. The artist didn't only find that island, but brought it out for the world to see. The first creatures discovered were 'Just Bananaz'. Originally inspired by a teeny-tiny toy banana. Little did she know that this tiny banana was going to have 7000+ friends to chill with in the future.";
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "Just Bananaz is working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
